export const REGISTER_SUCESS ="REGISTER_SUCESS";
export const REGISTER_FAIL ="REGISTER_FAIL";
export const LOGIN_FAIL ="LOGIN_FAIL ";
export const LOGIN_PASS ="LOGIN_PASS ";
export const LOGOUT ="LOGOUT ";
export const FETCH_ALL_USERS ="FETCH_ALL_USERS";
export const FETCH_ALL_USERS_FAILED ="FETCH_ALL_USERS_FAILED";
export const ALL_USERS ="ALL_USERS";
export const ALL_USERS_FAILED ="ALL_USERS_FAILED";
export const SEARCH_PASSED ="SEARCH_PASSED";
export const SEARCH_FAILED ="SEARCH_PASSED";


